### ISSUE TITLE
yinsh.net - Can't play with AI

### ISSUE THREAD

**Issue by enfrte** [danvinci/yinsh#1]
https://yinsh.net/

Selecting to play with AI outputs this `< Sorry, something went wrong >` and logs this in the console and 
`index-71a2709d.js:1 WebSocket connection to 'wss://yinsh.net/api' failed: `

**Comment by danvinci** [comment]
Docker service somehow stopped, hence the server wasn't responsive - not clear yet why it happened, but it's up and running again now.
